spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true


server:
  servlet:
    context-path: /sell

  port: 80



logging:
  pattern:
    console: "%d - %msg%n"
    file: /var/log/tomcat/sell


wechat:
  mpAppId: wx6563e05704e85ed5
  mpAppsecret: 33876fb72c825e1a14c8d104b092dcab

